// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqwrgeynjntjsgrqzewo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxd3JnZXluam50anNncnF6ZXdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NjU4MzksImV4cCI6MjA2NjU0MTgzOX0.MDtdEOLQ-VLn-U5t3nSxfE7Sc3gGWrZ7spBQx7CRi74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);